# 🪖 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [46]:
# initial setting
import tensorflow as tf
tf.__version__
import numpy as np

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

In [17]:
# Create a vector
vector = tf.constant([9, 7])

# Create a scalar
scalar = tf.constant(8)

# Create a matrix
matrix_1 = tf.constant([[1, 2],
                      [3, 4]])

matrix_2 = tf.constant([[7, 8],
                        [9, 10],
                        [11, 12]])

# create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

vector, scalar, matrix_1, matrix_2, tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 7], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

### 2. Find the shape, rank and size of the tensors you created in 1.

In [20]:
# shape, rank, size
tensor.shape, tensor.ndim , tf.size(tensor)

(TensorShape([3, 2, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=18>)

###3.Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [40]:
# Using tf.random.uniform to create random values between 0 and 1 and set_seed =  42
tf.random.set_seed(42)

A = tf.random.uniform(shape=[5, 300])
B = tf.random.uniform(shape=[5, 300])

In [42]:
A, A.shape, B, B.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

### 4.Multiply the two tensors you created in 3 using matrix multiplication.

In [44]:
# using tf.mtmul() and  tf.transpose() shape of B
tf.matmul(A, tf.transpose(B))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33344 , 73.40498 , 77.15962 , 73.98368 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.085266, 69.06406 , 74.307755, 72.27616 , 76.05668 ],
       [85.056885, 74.266266, 78.00687 , 74.88678 , 83.13418 ]],
      dtype=float32)>

### 5.Multiply the two tensors you created in 3 using dot product.

In [45]:
# using tf.tensordot() tf.transpose() shape of B and config axes=1
tf.tensordot(A, tf.transpose(B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33344 , 73.40498 , 77.15962 , 73.98368 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.085266, 69.06406 , 74.307755, 72.27616 , 76.05668 ],
       [85.056885, 74.266266, 78.00687 , 74.88678 , 83.13418 ]],
      dtype=float32)>

### 6.Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [48]:
# using tf.random.uniform()
# set_seed = 42
tf.random.set_seed(42)

C = tf.random.uniform(shape=[224, 224, 3])
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

### 7.Find the min and max values of the tensor you created in 6 along the first axis.

In [50]:
# find the minimum using tf.reduce_min()
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>

In [51]:
# find the maximum using tf.reduce_max()
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.999998>

### 8.Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [55]:
# Create tensor with random values of shape [1, 224, 244, 3]
# set seed = 42
tf.random.set_seed(42)

# using tf.random.uniform and set shape = [1, 244, 244, 3] containing to D
D = tf.random.uniform(shape=[1, 244, 244, 3])
D, D.shape

(<tf.Tensor: shape=(1, 244, 244, 3), dtype=float32, numpy=
 array([[[[0.6645621 , 0.44100678, 0.3528825 ],
          [0.46448255, 0.03366041, 0.68467236],
          [0.74011743, 0.8724445 , 0.22632635],
          ...,
          [0.14993274, 0.95743346, 0.0678556 ],
          [0.33755875, 0.2586832 , 0.31682265],
          [0.12932086, 0.6521549 , 0.6951654 ]],
 
         [[0.26241148, 0.36942792, 0.53326666],
          [0.2040397 , 0.21521878, 0.48851562],
          [0.5410471 , 0.55548096, 0.46440542],
          ...,
          [0.9536427 , 0.66850245, 0.50709856],
          [0.560426  , 0.6647233 , 0.1626333 ],
          [0.56197023, 0.4659928 , 0.8837141 ]],
 
         [[0.67773116, 0.88375974, 0.7615204 ],
          [0.53757155, 0.5554961 , 0.3356905 ],
          [0.7514802 , 0.10988402, 0.46292984],
          ...,
          [0.28655422, 0.00708723, 0.39797664],
          [0.32293415, 0.68600273, 0.2258904 ],
          [0.3624704 , 0.2741145 , 0.6718725 ]],
 
         ...,
 
       

In [56]:
# using tf.squeeze() to change shape
D_squeeze = tf.squeeze(D)
D_squeeze, D_squeeze.shape

(<tf.Tensor: shape=(244, 244, 3), dtype=float32, numpy=
 array([[[0.6645621 , 0.44100678, 0.3528825 ],
         [0.46448255, 0.03366041, 0.68467236],
         [0.74011743, 0.8724445 , 0.22632635],
         ...,
         [0.14993274, 0.95743346, 0.0678556 ],
         [0.33755875, 0.2586832 , 0.31682265],
         [0.12932086, 0.6521549 , 0.6951654 ]],
 
        [[0.26241148, 0.36942792, 0.53326666],
         [0.2040397 , 0.21521878, 0.48851562],
         [0.5410471 , 0.55548096, 0.46440542],
         ...,
         [0.9536427 , 0.66850245, 0.50709856],
         [0.560426  , 0.6647233 , 0.1626333 ],
         [0.56197023, 0.4659928 , 0.8837141 ]],
 
        [[0.67773116, 0.88375974, 0.7615204 ],
         [0.53757155, 0.5554961 , 0.3356905 ],
         [0.7514802 , 0.10988402, 0.46292984],
         ...,
         [0.28655422, 0.00708723, 0.39797664],
         [0.32293415, 0.68600273, 0.2258904 ],
         [0.3624704 , 0.2741145 , 0.6718725 ]],
 
        ...,
 
        [[0.1581651 , 0.0120461 

### 9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [59]:
# create a tensor with shape 10
# set seed = 42
tf.random.set_seed(42)

# using tf.random.uniform() to create tensor
E = tf.random.uniform(shape=[10])
E

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
      dtype=float32)>

In [62]:
# Find the index which has the maximum using tf.argmax() in tensor E
E[tf.argmax(E)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8724445>

# 10.One-hot encode the tensor you created in 9.

In [73]:
# One-hot encoder using tf.one_hot()
# change dtype from float to int32
E = tf.cast(E, dtype=tf.int32)

# using tf.one_hot() to encode chage the shape to one hot tensor
tf.one_hot(E, depth=3)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)>